-- Saisir ici vos instructions ddl (executables a partir de grhum ou d'un user dba)
DROP SEQUENCE GRHUM.RG_RAPPORT_SEQ;
DROP SEQUENCE GRHUM.RG_RELEVE_ANNOMALIE_SEQ;
DROP TABLE GRHUM.RG_RAPPORT CASCADE CONSTRAINTS;
DROP TABLE GRHUM.RG_RELEVE_ANNOMALIE CASCADE CONSTRAINTS;